version: '3.7'

services:

  frontend:
    image: ghcr.io/m4rc02u1f4a4/ytrss-frontend:latest
    restart: always
    environment:
      REACT_APP_API_BASE_URL: http://<HOST_IP>:5001
    ports:
      - 8080:8080


  updater:
    image: alpine
    environment:
      REACT_APP_API_BASE_URL: http://backend:5001
    command: 
      - /bin/sh
      - -c
      - |
        apk --update add curl && \
        echo $${REACT_APP_API_BASE_URL} && \
        echo "0 0 */1 * * curl -X GET $${REACT_APP_API_BASE_URL}/update/channels" > /var/spool/cron/crontabs/root && \
        echo "0 */1 * * * curl -X GET $${REACT_APP_API_BASE_URL}/update/videos" >> /var/spool/cron/crontabs/root && \
        echo "0 0 */1 * * curl -X GET $${REACT_APP_API_BASE_URL}/clean/videos" >> /var/spool/cron/crontabs/root && \
        crond -l 2 -f
    depends_on:
      - backend


  backend:
    image: ghcr.io/m4rc02u1f4a4/ytrss-backend:latest
    restart: always
    environment:
      MONGODB_HOST: db
      MONGODB_PORT: 27017
      G_API_KEY: <GOOGLE_API_KEY>
      PYTHONUNBUFFERED: 1
    ports:
      - 5001:5001
    depends_on:
      - db


  db:
    image: mongo
    restart: always
    environment:
      TZ: Europe/Rome
    volumes:
      - ./docker_db:/data/db