version: '3.7'

services:

  ytrss:
    build: 
      context: .
    restart: always
    environment:
      MONGODB_USERNAME: changeme
      MONGODB_PASSWORD: changeme
      MONGODB_HOST: db
      MONGODB_PORT: 27017
      G_API_KEY: API KEY
      PYTHONUNBUFFERED: 1
    ports:
      - 80:5001
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: changeme
      MONGO_INITDB_ROOT_PASSWORD: changeme
      TZ: Europe/Rome
    # ports:
    #   - 27017:27017
    volumes:
      - ./docker_db:/data/db